# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true

group=cc.turtl.turtlshell

# API
mc_version = 1.21.1
parchment_version = 2024.07.28@zip
# Used in mod files
java_version = 21

mod_id=turtlshell
mod_display_name=turtlshell
mod_version=1.0.0
mod_author=megaturtl
mod_description=The base of megaturtl's Minecraft mods.
snapshot=true

fabric.loom.multiProjectOptimisation=false

# Mod implementation dependencies
yacl_version=3.8.1+1.21.1