org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_id=turtlshell
mod_display_name=turtlshell
mod_version=1.0.0
mod_author=megaturtl
mod_desc=The base of megaturtl's Minecraft mods.
maven_group=cc.turtl

enabled_platforms=fabric,neoforge

minecraft_version=1.21.1

# Platform dependencies
parchment_version=parchment-1.21:2024.07.28@zip
loom_version=1.13-SNAPSHOT
architectury_plugin_version=3.4-SNAPSHOT

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.116.9+1.21.1
mod_menu_version=11.0.3

# Forge
neoforge_version=21.1.182

# Mod implementation dependencies
yacl_version=3.8.1+1.21.1

# Other dependencies
junit_version=6.0.3
mockito_version=5.22.0
