modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_display_name}"
authors = "${mod_author}"
description = "${mod_description}"
logoFile="assets/turtlshell/icon.png"

[[dependencies.turtlshell]]
modId = "minecraft"
mandatory = true
versionRange="[${minecraft_version}]"

[[dependencies.turtlshell]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"

[[dependencies.turtlshell]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.6.1,)"
side = "CLIENT"

[[mixins]]
config = "turtlshell-neoforge.mixins.json"
[[mixins]]
config = "turtlshell-common.mixins.json"
